name: qrmfold
channels:
  - conda-forge
dependencies:
  - python
  - ipykernel
  - ipywidgets
  - matplotlib
  - pandas
  - pytest
  - snakeviz
  - sage
  - hatch
  - pip
  - pip:
      - stim
      - sinter
      - reedmuller