[project]
name = "qrmfold"
version = "0.5.6"
description = "A Python package to generate fold-transversal gates in the quantum Reed-Muller code."
authors = [{name="Tim Chan", email="timwlc@icloud.com"}]
dependencies = [
    "ipykernel",
    "ipywidgets",
    "matplotlib",
    "pandas",
    "pytest",
    "snakeviz",
    "stim",
    "sinter",
]
requires-python = ">=3.13"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"